# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# プロジェクト固有の調整のみ
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Rails:
  Style/StringLiterals:
    EnforcedStyle: single_quotes
