name: 'farmy_api'

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    stdin_open: true
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
      - selenium
      - mysql
      - redis

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

  mysql:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "${DATABASE_BIND_ADDRESS}:${DATABASE_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

  redis:
    image: redis:8.0
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data

  sidekiq:
    build: .
    env_file:
      - ../.env  # env_fileを追加
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data:
  redis-data:
